pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Vercel
    actions:
      merge:
        method: merge
  - name: automatic merge from dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Vercel
      - base=(master|main)
    actions:
      merge:
        method: merge
        strict: smart
        priority: low
